### PR TITLE
Protocol column of Wireshark now shows "MVR".

### PR DESCRIPTION
**Pull request by lukechikkala**

### CODE REVIEW

**Comment by petrvanekrobe** [comment]
Hello @lukechikkala , thank you.

1) The file attribution says  --  Luke Chikkala @ MA Lighting International GmbH, but i cannot assert this identity in any way from your GitHub account. You can email me from you work email to my work email (my email is in git logs), to confirm this please.

2) Code formatting should not be an opinionated process. I would suggest to use a standard formatter, like other languages do (go-fmt for go, black/ruff for python...). For lua, [StyLua exists](https://github.com/JohnnyMorganz/StyLua), this will remove ambiguity and makes future diffing simpler.

3) Thank you for the enhancements. The provided pcap is good, to prove that the dissector works is still working.

**Comment by lukechikkala** [comment]
Hi @petrvanekrobe ,

2. I will look into StyLua, for the next pull requests, if there should be any.

Thank you.

**Comment by petrvanekrobe** [comment]
Hello @lukechikkala , i wanted to check with you whether i should merge this as is or if you have any further plans with this. Thank you.

**Comment by lukechikkala** [comment]
Hi @petrvanekrobe, as for now, I do not have further plans unless there are fundamental changes to the protocol itself 🙂
You can merge it if you have no concerns.

**Comment by petrvanekrobe** [comment]
Thank you

**Pull request merged**
