### PR TITLE
Proposal for DMX Profiles and additional Attributes Units

### PR DESCRIPTION
**Pull request by moritzstaffel**

### CODE REVIEW

**Comment by LxLasso** [comment]
I have some doubts about the splines. Assuming that you are creating a GDTF file for a fixture you can take measurements for, then you are trying to create a spline to matches them. I would probably consider it worth avoiding the risk of GDTF consumers getting the spline interpolation wrong by taking more samples instead. Optionally, I could use a spline editor "on the side" to create an approximation and then load the computed values for each DMX step in the actual GDTF. If you take the more hardline approach of saying that consumers need to get the spline interpolation right, then I think you better provides some explicit maths as to the correct way of performing the spline interpolation.

I'm also left wondering whether a `DmxProfile` can be applied in reverse by using a `ChannelFunction` `min` value that is larger than the `max` value. It's often the case with wheels that there is a speed curve that appears twice on a channel, one being mirrored.

**Comment by moritzstaffel** [comment]
> I have some doubts about the splines. Assuming that you are creating a GDTF file for a fixture you can take measurements for, then you are trying to create a spline to match them. I would probably consider it worth avoiding the risk of GDTF consumers getting the spline interpolation wrong by taking more samples instead. Optionally, I could use a spline editor "on the side" to create an approximation and then load the computed values for each DMX step in the actual GDTF. If you take the more hardline approach of saying that consumers need to get the spline interpolation right, then I think you better provides some explicit maths as to the correct way of performing the spline interpolation.

The spline is an option, the interpolation would be still possible. The splines can be generated with the fixture builder, I don't aspect user to do the math.

**Comment by moritzstaffel** [comment]
>I'm also left wondering whether a DmxProfile can be applied in reverse by using a ChannelFunction min value that is larger than the max value. It's often the case with wheels that there is a speed curve that appears twice on a channel, one being mirrored.

**Comment by vanous** [comment]
Adding a link to the info on how the ICC format deals with curve profiles, mentioned in the interfacing meeting.

Table 65 on page 69 has an overview of "parametricCurveType":
https://www.color.org/specification/ICC1v43_2010-12.pdf 

provided by @LxLasso via forum.

**Comment by petrvanekrobe** [comment]
Adding a link to the info on how the ICC format deals with curve profiles, mentioned in the interfacing meeting.

Table 65 on page 69 has an overview of "parametricCurveType":
https://www.color.org/specification/ICC1v43_2010-12.pdf 

provided by @LxLasso via forum. Managing multiple identities on GH is a nightmare...

**Pull request merged**
