### PR TITLE
Add proposal for gltf

### PR DESCRIPTION
**Pull request by moritzstaffel**

### CODE REVIEW

**Comment by LxLasso** [comment]
As noted in the interfacing meeting yesterday, I don't think that including more than one GLB file in a GDTF or MVR archive is brilliant. An important reason for moving towards glTF is to support PBR materials, which means textures. If the same material is used in more than one GLB file, any textures used by the material will be duplicated. In MVR that is particularly bad as you may have thousands of instances of objects using the same material.

I suggest that when referring to a GLB, the name of a node is also given.

If that doesn't work, then perhaps not using GLB but rather glTF could be an option as the textures would then be separate, shareable, entities.

**Comment by RichardTea** [comment]
The only difference between the GLB and GLTF packaging is that a GLB file embeds a single binary blob, while GLTF will usually refer to an external BIN file.

Both packages contain the exact same data, both may refer to external data blobs.
It is usual for both packaging schemes to place the texture image data into external PNG or JPEG files.

I fully agree that the MVR/GDTF references should include the ID (numeric) and Name (string) of the Node within the specified glTF.

**Comment by moritzstaffel** [comment]
The preferred but not required was also what we where discussing.

**Comment by RichardTea** [comment]
I agree with Lars that the MVR/GDTF references should optionally include the Name (string) of the Scene or Node within the specified glTF file.

If a name is given, then that specific Scene (with hierarchy) or Node (without hierarchy) shall be used for the referred section.

If no name is given, then the Default Scene node hierarchy is to be used in its entirety.

This would allow two things:
1. Fixtures can be provided as a single, pre-assembled glTF file that's possible to create, export and import in 3D modelling tools such as Blender. This greatly simplifies authoring of the 3D model, which is the main stumbling block with uptake of GDTF.
2. A single glTF file can provide a 'library' of related 3D scenes or objects for assembly, de-duplicating any shared mesh data.

**Pull request merged**
